default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

default_local: &default_local
  host: db
  username: postgres

development:
  <<: *default
  <<: *default_local
  database: ruby-rails-sample_development

test:
  <<: *default
  <<: *default_local
  database: ruby-rails-sample_test

production:
  <<: *default
  database: ruby-rails-sample_production
